version: '3.7'

services:
  nipt-nginx-service:
    build:
      context: .
      dockerfile: ./docker/dev/nginx.dev.dockerfile
    image: cgu/nginx_dev:0.5.2
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - nipt-web-service
    networks:
      - private
  nipt-web-service:
    build:
      context: .
      dockerfile: ./docker/dev/development.dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./niptviewer:/usr/src/app:Z
      - static_volume:/usr/src/app/staticfiles:rw
    expose:
      - 8000
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=niptviewer.settingsdev
    env_file:
      - ./docker/dev/.env_web
    depends_on:
      - nipt-db-service
    networks:
      - private
  nipt-db-service:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker/dev/.env_db
    networks:
      - private

volumes:
  postgres_data:
  static_volume:

networks:
  private:
