version: '3.7'

services:
  nipt-nginx-service:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.prod.dockerfile
    image: cgu/nginx_https:0.5.8
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - /etc/letsencrypt/live/cgu.igp.uu.se:/etc/letsencrypt/live/cgu.igp.uu.se
    depends_on:
      - nipt-web-service
    networks:
      - private
  nipt-web-service:
    build:
      context: .
      dockerfile: ./dockerfiles/production.dockerfile
    image: smeds84/niptviewer:1.1.0
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - nipt-db-service
    networks:
      - private
    #dns_search: .

  nipt-db-service:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    networks:
      - private


volumes:
  postgres_data:
  static_volume:

networks:
  private:
