wget https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.6/nv.d3.min.css -O niptviewer/assets/css/nv.d3.min.1.8.6.css
wget https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.6/nv.d3.min.css.map -O niptviewer/assets/css/nv.d3.min.css.map
wget https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js -O niptviewer/assets/js/d3.min.3.5.2.js
wget https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.6/nv.d3.js.map -O niptviewer/assets/js/nv.d3.min.js.map
wget https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.4.0/clipboard.min.js -O iptviewer/assets/js/clipboard.min.js
wget https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js -O niptviewer/assets/js/jquery-ui.min.js
wget https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.6/nv.d3.min.js -O niptviewer/assets/js/nv.d3.min.1.8.6.js
wget https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css -O niptviewer/assets/css/materialize.min.1.0.0.css
wget https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js -O niptviewer/assets/js/materialize.min.1.0.0.js
wget https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js -O niptviewer/assets/js/jquery-2.1.1.min.js
wget https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.map -O niptviewer/assets/js/jquery.min.map
wget https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.4.0/clipboard.min.js -O niptviewer/assets/js/clipboard.min.js
