apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2021-10-25T10:42:09Z
  labels:
    app: niptviewer
  name: niptviewer
spec:
  containers:
  - name: nginx
    image: smeds84/nginx:1.0.0
    ports:
    - containerPort: 80
      hostport: 8081
      protocol: TCP
    - containerPort: 443
      hostport: 4443
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
  - name: web
    image: smeds84/niptviewer:1.1.0
    env:
    - name: DJANGO_ALLOWED_HOSTS
      value: gollum.lul.se 127.0.0.1 localhost
    - name: DEBUG
      value: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
status: {}
