site_name: NIPTViewer
site_url: https://niptviewer.readthedocs.io
nav:
  - Introduction: index.md
  - Running/Deploying:
    - Development: development.md
    - Production: production.md
  - Configuration:
    - Server: server_configuration.md
    - User admininstration: user_configuration.md
  - Visualisation: 
    - Introduction: visualisation_introduction.md
    - Result: visualisation_result.md
    - QC: visualisation_qc.md
    - PDF: visualisation_pdf.md
  - About: 
    - about.md
theme: readthedocs
plugins:
#  - search
#  - mkdocs-simple-hooks:
#      hooks:
#        on_pre_build: "docs.hooks:copy_plot_scripts"
extra_javascript:
  - static/chromosome_line_chart.js
#  - static/grouped_barchart.js
#  - static/line_chart.js
#  - static/scatter_chart.js
