# Generated by Django 3.1.1 on 2020-09-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='software_version',
            field=models.CharField(default='1.4.0', help_text='Illumina analysis software version', max_length=10),
            preserve_default=False,
        ),
    ]
