# Generated by Django 3.1.1 on 2020-09-30 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0002_batchrun_software_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
