# Generated by Django 3.1.1 on 2020-09-30 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0003_flowcell_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='run_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
