# Generated by Django 3.1.1 on 2020-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0004_flowcell_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplesrundata',
            name='sample_id',
            field=models.CharField(default='test', help_text='SampleID', max_length=10),
            preserve_default=False,
        ),
    ]
