# Generated by Django 3.1.1 on 2020-10-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0005_samplesrundata_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_13',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Normalized Chromosomal Value (z-score) 13',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_18',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Normalized Chromosomal Value (z-score) 18',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_21',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Normalized Chromosomal Value (z-score) 21',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_X',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Normalized Chromosomal Value (z-score) X',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_Y',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Normalized Chromosomal Value (z-score) Y',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_13',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Chromosomal Ratio 13',
                                      max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_18',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Chromosomal Ratio 18',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_21',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Chromosomal Ratio 21',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_X',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Chromosomal Ratio X',
                                      max_digits=15,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_y',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Chromosomal Ratio Y',
                                      max_digits=15,
                                      null=True),
        ),
    ]
