# Generated by Django 3.1.1 on 2020-10-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0006_auto_20201029_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesrundata',
            name='ff_formatted',
            field=models.DecimalField(decimal_places=10,
                                      help_text='Estimated fetal component of cfDNA recovered by the assay. Reported as a' +
                                                ' discreet, rounded percentage that provides additional information for each' +
                                                ' sample.',
                                      max_digits=15,
                                      null=True),
        ),
    ]
