# Generated by Django 3.1.1 on 2020-11-03 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataprocessor', '0008_auto_20201103_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='uploading_user',
            field=models.ForeignKey(default=1,
                                    help_text='User that uploaded the flowcell identification.',
                                    on_delete=django.db.models.deletion.RESTRICT,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
