# Generated by Django 3.1.1 on 2020-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0009_flowcell_uploading_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='qc_status',
            field=models.CharField(default='PASS', help_text='QC summary for samples', max_length=20),
        ),
    ]
