# Generated by Django 3.1.1 on 2020-11-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0011_auto_20201108_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcell',
            name='qc_status',
            field=models.CharField(default='PASS', help_text='QC summary for samples', max_length=200),
        ),
    ]
