# Generated by Django 3.1.1 on 2020-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0012_auto_20201108_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplesrundata',
            name='sample_project',
            field=models.CharField(default='', help_text='SampleID', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='median_13',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='median_18',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='median_21',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='median_x',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='median_y',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr10_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr11_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr12_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr13_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr14_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr15_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr16_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr17_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr18_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr19_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr1_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr20_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr21_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr22_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr2_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr3_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr4_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr5_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr6_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr7_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr8_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chr9_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chrx_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='chry_coverage',
            field=models.DecimalField(decimal_places=20, help_text='Normalized coverage of each chromosome used in evaluation of chromosomal ratios', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='description',
            field=models.TextField(default='', help_text='Description.'),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ff_formatted',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Estimated fetal component of cfDNA recovered by the assay. Reported as a discreet, rounded percentage that provides additional information for each sample.', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='gc_bias',
            field=models.DecimalField(decimal_places=20, help_text='Residual GC bias in the read distribution after correction', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='gcr2',
            field=models.DecimalField(decimal_places=20, help_text='R2 of the GC correction (percentage of variance explained by GC correction)', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='library_nm',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncd_13',
            field=models.DecimalField(decimal_places=20, help_text='Likelihood score for chromosome 13 denominators', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncd_18',
            field=models.DecimalField(decimal_places=20, help_text='Likelihood score for chromosome 18 denominators', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncd_21',
            field=models.DecimalField(decimal_places=20, help_text='Likelihood score for chromosome 21 denominators', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncd_x',
            field=models.DecimalField(decimal_places=20, help_text='Likelihood score for chromosome X denominators', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncd_y',
            field=models.DecimalField(decimal_places=20, help_text='Likelihood score for chromosome Y denominators', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_13',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Normalized Chromosomal Value (z-score) 13', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_18',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Normalized Chromosomal Value (z-score) 18', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_21',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Normalized Chromosomal Value (z-score) 21', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_X',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Normalized Chromosomal Value (z-score) X', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ncv_Y',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Normalized Chromosomal Value (z-score) Y', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='non_excluded_sites_2_tags',
            field=models.DecimalField(decimal_places=20, help_text='Ratio of NonExcludedSites to tags', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='perfect_match_tags_2_tags',
            field=models.DecimalField(decimal_places=20, help_text='Ratio of perfectly mapped tags to all tags', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='qc_failure',
            field=models.TextField(default='', help_text='Description.'),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='qc_warning',
            field=models.TextField(default='', help_text='Description.'),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_13',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Chromosomal Ratio 13', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_18',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Chromosomal Ratio 18', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_21',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Chromosomal Ratio 21', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_X',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Chromosomal Ratio X', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='ratio_y',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Chromosomal Ratio Y', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='tags_2_indexed_reads',
            field=models.DecimalField(decimal_places=20, help_text='Ratio of tags to indexed reads', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='total_indexed_reads_2_clusters',
            field=models.DecimalField(decimal_places=20, help_text='Ratio of indexed reads to clusters (Reported per flow cell)', max_digits=25),
        ),
        migrations.AlterField(
            model_name='samplesrundata',
            name='total_reads_2_clusters',
            field=models.DecimalField(decimal_places=20, help_text='Ratio of recovered reads to number of clusters across lanes (Reported per flow cell)', max_digits=25),
        ),
    ]
