# Generated by Django 3.1.1 on 2021-06-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0013_auto_20201124_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchrun',
            name='median_18',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='median_x',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='median_y',
            field=models.DecimalField(decimal_places=20, help_text='Batch median of chromosomal ratios for putative diploid samples. ChrX and chrY are based on putative female samples only.', max_digits=25),
        ),
    ]
