# Generated by Django 3.1.1 on 2021-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0014_auto_20210623_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope', models.DecimalField(decimal_places=5, help_text='Slope of line', max_digits=15)),
                ('intercept', models.DecimalField(decimal_places=5, help_text='Intercept point', max_digits=15)),
                ('stderr', models.DecimalField(decimal_places=5, help_text='Stderr', max_digits=15)),
                ('stdev', models.DecimalField(decimal_places=5, help_text='Stderr', max_digits=15)),
                ('p_value', models.DecimalField(decimal_places=5, help_text='P value', max_digits=15)),
                ('r_value', models.DecimalField(decimal_places=5, help_text='R value', max_digits=15)),
                ('plot_type', models.CharField(help_text='Comparison type', max_length=20, unique=True)),
            ],
        ),
    ]
