FROM ubuntu:focal

ENV LANG C.UTF-8
ENV TZ=Europe/Stockholm
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && apt-get -y upgrade
RUN apt-get install -y python3 python3-pip python3-dev wkhtmltopdf

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

ENV DOCKYARD_SRVPROJ=/srv/app
COPY ./dockerfiles/entrypoint.sh /entrypoint.sh
WORKDIR $DOCKYARD_SRVPROJ
ENTRYPOINT ["/entrypoint.sh"]
