apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2021-10-25T10:42:09Z
  labels:
    app: niptviewer
  name: niptviewer
spec:
  containers:
  - name: nginx-dev
    image: smeds84/nginx:1.1.0
    ports:
    - containerPort: 80
      hostport: 8001
      protocol: TCP
    - containerPort: 443
      hostport: 4443
      protocol: TCP
    volumeMounts:
     - name: staticfiles
       mountPath: /home/app/web/staticfiles
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
  - name: web-dev
    image: smeds84/niptviewer:v1.8.3
    env:
    - name: DJANGO_ALLOWED_HOSTS
      value: gollum.lul.se 127.0.0.1 localhost
    - name: DEBUG
      value: 0
    - name: "DATABASE"
      value: "mssql"
    - name: "SQL_ENGINE"
      value: "mssql"
    - name: "SQL_DATABASE"
      value: "niptviewer"
    - name: "SQL_HOST"
      value: "SQLH-DB-19"
    - name: "SQL_USER"
      value: "username_secret"
    - name: "SQL_PASSWORD"
      value: "password_secret"
    envFrom:
    - secretRef:
        name: user_secret
    - secretRef:
        name: password_secret
    volumeMounts:
     - name: staticfiles-dev
       mountPath: /home/app/web/staticfiles
     - name: staticfiles-dev
       mountPath: /staticfiles
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
  volumes:
    - name: staticfiles-dev
      persistentVolumeClaim:
        claimName: niptviewer-dev-staticfiles
  restartPolicy: Always


status: {}
