apiVersion: v1
kind: Service
metadata:
  name: nipt-nginx-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: nipt-nginx-container
status:
  loadBalancer: {}
