apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: staticfiles-data
  name: staticfiles-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
status: {}
