name: Publish to Docker Hub

on:
  push:
    branches:
      - dev
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    - run: echo "$GITHUB_BRANCH"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        name: smeds84/niptviewer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        buildargs: VERSION=$GITHUB_BRANCH
