name: Publish to Docker Hub

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    - run: echo "$GITHUB_BRANCH"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: smeds84/niptviewer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        buildargs: "VERSION=${{ env.GITHUB_BRANCH }}"
