on:
  push:
    branches:
      - master

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          default-branch: master

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0

      - name: Set up Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.16
        if: ${{ steps.release.outputs.release_created }}
        with:
          name: smeds84/niptviewer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          tags: "v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }},stable"
          buildargs: VERSION=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

